Project8/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('story8/', include(('story8.urls', 'story8'), namespace='story8')),
    # path('logout/', logoutView, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('story11/', include(('story11.urls', 'story11'), namespace='story11')),
]

story11/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views 
from django.conf import settings
from .views import get_data, index, addFav, unFav, get_book, logout



urlpatterns = [
    path('', index, name = 'index'),
    path('get_data/cari=<str:cari>', get_data, name = 'get_data'),
    path('logout/', logout, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('get_book/', get_book, name = 'get_book'),
    path('addFav/', addFav, name = 'addFav'),
    path('unFav/', unFav, name = 'unFav')
]

story8/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url 
from .views import index as landingpage
from .views import books, bookspage, check_email, add_subscriber, web_service, delete_user

urlpatterns = [
    path('', landingpage, name='landing-page'),
	path('books', books, name='books'),
    path('data', bookspage, name='bookspage'),
    path('check_email/', check_email, name = 'check_email'),
    path('add_subscriber/', add_subscriber, name = 'add_subscriber'),
    path('web_service/', web_service, name = 'web_service'),
    path('delete_user/', delete_user, name = 'delete_user')


]

story11/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	total_fav = models.IntegerField()
		

story8/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    email = models.EmailField(max_length = 100, unique = True)
    name = models.CharField(max_length = 100)
    password = models.CharField(max_length = 100)

story8/forms.py
from django import forms


class SubscribeForm(forms.Form):
    email = forms.EmailField(
        label = 'E-mail',
        required = True,
        max_length = 100,
        widget = forms.TextInput(attrs = {
            'name':'email',
            'placeholder':'Enter Email',
            'type':'text',
            'id':'emailForm'
        })
    )
    name = forms.CharField(
        label = 'Name',
        required = True,
        max_length = 100,
        widget = forms.TextInput(attrs = {
            'name':'name',
            'placeholder':'Enter Name',
            'type':'text',
            'id':'nameForm'
        })
    )
    password = forms.CharField(
        label = 'Password',
        required = True,
        max_length = 100,
        widget = forms.TextInput(attrs = {
            'name':'password',
            'placeholder':'Enter Password',
            'type':'password',
            'id':'passwordForm'
        })
    )

story11/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth import logout as logout_oauth
import requests
import json

# Create your views here.

first_log = True

def get_data(request, cari="quilting"):

    link = "https://www.googleapis.com/books/v1/volumes?q=" + cari
    data_final = requests.get(link).json()
    return JsonResponse(data_final)

def index(request):
    if  request.user.is_authenticated :
        if "liked_books" not in request.session:
            request.session["fullname"] = request.user.first_name + " " + request.user.last_name
            request.session["username"] = request.user.username
            request.session["email"] = request.user.email
            request.session["sessionid"] = request.session.session_key
            request.session['liked_books'] = []

        return render(request, 'list_book_user.html')
    else:
        request.session['liked_books'] = []
        return render(request, 'list_book_no_user.html') 

def get_book(request):
    return JsonResponse(request.session['liked_books'], safe = False)

def addFav(request):
    if request.method == "POST":
        liked_book_id = request.POST['liked_id']
        tmp_liked_books = request.session['liked_books']
        if liked_book_id not in tmp_liked_books:
            tmp_liked_books.append(liked_book_id)
            request.session['liked_books'] = tmp_liked_books

        return JsonResponse({'result' : 'success', 'status' : 200})

    return JsonResponse({"result" : "No Get Method", 'status' : 403})


def unFav(request):
    if request.method == "POST":
        liked_book_id = request.POST['liked_id']
        tmp_liked_books = request.session['liked_books']

        if liked_book_id in tmp_liked_books:
            tmp_liked_books.remove(liked_book_id)
            request.session['liked_books'] = tmp_liked_books

        return JsonResponse({'result' : 'success', 'status' : 200})
    
    return JsonResponse({"result" : "No Get Method", 'status' : 403})

def logout(request):
    logout_oauth(request)
    return redirect('story11:index')

story8/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login
import requests
import json


from .forms import SubscribeForm
from .models import Subscriber
from django.core.validators import validate_email
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

response = {}

def index(request):
	response = {
		'subsForm' : SubscribeForm
	}
	return render(request, 'index.html', response)

def books(request):
    # if request.user.is_authenticated:
    #     if 'fav' not in request.session:
    #         request.session['fav'] = 0
    #     jml = request.session['fav']
    #     response['fav'] = jml
    #     if 'nama' not in request.session:
    #         request.session['nama'] = request.user.username
    #     if 'email' not in request.session:
    #         request.session['email'] = request.user.email
    # return render(request, 'books.html', response)
    return render(request, 'books.html', response)

def bookspage(request, cari='quilting'):
	link = 'https://www.googleapis.com/books/v1/volumes?q=' + cari
	daftar = requests.get(link).json()
	return JsonResponse(daftar)

def check_email(request):
    try:
        print(request.POST['email'])
        validate_email(request.POST['email'])
    except:
        return JsonResponse(
        	{
        	'message':'Email format is wrong!',
            'status':'fail'
            })

    exist = Subscriber.objects.filter(email=request.POST['email'])

    if exist:
        return JsonResponse(
        	{
            'message':'Email already exist',
            'status':'fail'
        	})
    
    return JsonResponse(
    	{
        'message':'Email can be used',
        'status':'success'
    	})


def add_subscriber(request):
    if (request.method == "POST"):
        subscriber = Subscriber(
            email = request.POST['email'],
            name = request.POST['name'],
            password = request.POST['password']   
        )
        subscriber.save()
        return JsonResponse({
            'message':'Subscribe success!'
        }, status = 200)
    else:
        return JsonResponse({
            'message':"There's no GET method here!"
        }, status = 403)

def web_service(request):
	data_user = Subscriber.objects.all().values('name', 'email')
	data = list(data_user)
	return JsonResponse(data, safe = False)

def delete_user(request):
	print('Login')
	print(request.POST['email'])
	select_user = Subscriber.objects.filter(email=request.POST['email'], password=request.POST['password'])

	if select_user:
		select_user.delete()
		return JsonResponse(
			{
			'message':request.POST['email'] + 'removed!',
			'deleted':True
			})

		return JsonResponse(
			{
			'message':'Incorrect password',
			'deleted':False
			})


'''def my_view(request):
	username = request.POST['username']
	password = request.POST['password']''
	user = authenticate(request, username=username, password=password)
	if user is not None:
		return JsonResponse({
            'message':'Login success!'
        }, status = 200)
	else:
		return JsonResponse({
            'message':"There's no GET method here!"
        }, status = 403)'''

story11/templates/list_book_no_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 11: Books</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/book_noUser.js' %}"></script>
</head>
<body>
    <header>{% include 'navbar.html'%}</header>
    <div class="container-fluid h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-11">
                <div class="row">
                    <div class="col-sm-12 text-center" style="padding-top:20px;">
                        <input type="button" class="btn" value="Login with Google" onclick="window.location.href='{% url 'social:begin' 'google-oauth2' %}'">
                        <a href=""></a><br>
                        
                    </div>
                    <div class="col-sm-12" style="padding-top: 5vh; text-align:left; font-size: 20px; font-weight: bold">
                        <p class="judul" style="font-size: 47px; margin-bottom:-1vh"><strong>Books</strong></p>
                    </div>
                </div>
                <div class="text-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <!--end of col-->
                        <div class="col">
                            <input class="form-control form-control-lg form-control-borderless" name="pencarian" type="search" placeholder="Search for books..">
                        </div>
                        <!--end of col-->
                        <div class="col-auto">
                            <button class="btn btn-lg btn-success" type="submit" onclick="search()">Search</button>
                        </div>
                </div>
                

                <div class="roundedrec" style="margin-bottom:6.7%;">
                    <div class="insiderec">
                        <div class="table-responsive">
                            <table id="demo" class="table" style="font-size: 15px;">
                                <thead>
                                    <tr class="table text-center">
                                        <th scope="col" class="align-middle">No</th>
                                        <th scope="col" class="align-middle">Cover</th>
                                        <th scope="col" class="align-middle">Title</th>
                                        <th scope="col" class="align-middle">Authors</th>
                                        <th scope="col" class="align-middle">Publisher</th>
                                        <th scope="col" class="align-middle">Published Date</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</body>
</html>

story11/templates/list_book_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 11: Books</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/book_user.js' %}"></script>
</head>
<body>
    <header>{% include 'navbar.html'%}</header>
    {% csrf_token %}
    <div class="container-fluid h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-11">
                <div class="row">
                    <div class="col-sm-10">
                        {% if user.is_authenticated %}
                            <br>
                            <p class="display-4" style="font-size: 24px; font-weight: bold" >Hello, {{ user.username }}</p>
                            <a class="lead" href="{% url 'story11:logout' %}">Log out</a>
                        {% else %}
                            <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
                        {% endif %}
                        <p class="judul" style="font-size: 47px; padding-top: 50px; margin-bottom:-1vh"><strong>Story 11: Books</strong></p>
                        <text >Favourite(s):</text>
                        <text id="counter"> {{ total_liked }} </text>
                    </div>
                    <div class="col-sm-2" style="padding-top: 10.5vh; text-align:right; font-size: 20px; font-weight: bold">
                        
                    </div>
                </div>
                <div class="text-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <!--end of col-->
                        <div class="col">
                            <input class="form-control form-control-lg form-control-borderless" name="pencarian" type="search" placeholder="Search for books..">
                        </div>
                        <!--end of col-->
                        <div class="col-auto">
                            <button class="btn btn-lg btn-success" type="submit" onclick="search()">Search</button>
                        </div>
                </div>
                

                <div class="roundedrec" style="margin-bottom:6.7%;">
                    <div class="insiderec">
                        <div class="table-responsive">
                            <table id="demo" class="table" style="font-size: 15px;">
                                <thead>
                                    <tr class="table text-center">
                                        <th scope="col" class="align-middle">No</th>
                                        <th scope="col" class="align-middle">Cover</th>
                                        <th scope="col" class="align-middle">Title</th>
                                        <th scope="col" class="align-middle">Authors</th>
                                        <th scope="col" class="align-middle">Publisher</th>
                                        <th scope="col" class="align-middle">Published Date</th>
                                        <th scope="col" class="align-middle">Add to Favourite(s)</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</body>
</html>

story8/templates/books.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>Books</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    
    <link rel="stylesheet" href={% static "css/style.css" %}>
    
    <script src="{% static 'js/javasc.js' %}"></script>  
</head>

<body>

    <header>
        {% include 'navbar.html' %}
    </header>

       


    <br><br><br>
    <div style="margin: 10px">
    <h1>Books</h1>
    <h5>Favorite: <a id="jml">0</a></h5>
    <br>
    <input type="text" id="sbar" placeholder=" Search for books.." style="margin-left: auto; margin-right: auto; display: block;">
    </div>
    <br><br>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Book</th>
          <th scope="col">Title</th>
          <th scope="col">Authors</th>
          <th scope="col">Description</th>
          <th>Add to Favorite</th>
        </tr>
      </thead>
      <tbody id="bt">    
      </tbody>
    </table>

</body>
</html>

story8/templates/index.html
<!DOCTYPE html>
<html>
{% load static %}
{% load crispy_forms_tags %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/ >X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<script src="{% static 'js/javasc.js' %}"></script>
<script src="{% static 'js/subscribe.js' %}"></script>

</head>

<body>

<div id="overlay" >
    <div id="overlay-content">
        This will all vanish in 2 seconds ... 
    </div>
</div>

<header>
    {% include 'navbar.html' %}
</header>

<div class="content">
<h1 style="margin: 10px">Profile</h1>
<div class="flip-card" style="padding-left: 150px; padding-right: 150px;">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/40987244_2051814751496829_6527488229854150656_n.jpg?_nc_cat=0&oh=6c47f2084bf646631293ab8ebb6aef70&oe=5C22D185" alt="abang" style="width:300px;height:300px; ">
    </div>
    <div class="flip-card-back">
      <h2>S.A.R Syifa</h2> 
      <p>sarsyifa@gmail.com</p> 
      <p>Universitas Indonesia</p>
    </div>
  </div>
</div>

<h2 style="margin: 10px">Siti Aulia Rahmatussyifa</h2>


<button class="accordion">Organisasi</button>
<div class="panel">
  <p>BEM Fasilkom UI 2018 - Staf Departemen Olahraga</p>
</div>

<button class="accordion">Kepanitiaan</button>
<div class="panel">
  <p>CS League 2018 - Staf Pertandingan</p>
  <p>Wisuda Genap Fasilkom UI 2018 - Staf Dokumentasi</p>
</div>

<button class="accordion">Interest</button>
<div class="panel">
  <p>Travel</p>
  <p>Music</p>
  <p>Photography</p>
  <p>Sport</p>
</div>
<br>
<button type="button" onclick="body.style.backgroundColor='#161d1e'; body.style.color='white'; document.getElementsByClassName('flip-card-back')='#47525E'">Nightmode</button>
<button type="button" onclick="body.style.backgroundColor='white'; body.style.color='black'; document.getElementsByClassName('flip-card-back')='black'">Normal</button>
<br><br>

  <h3>Yakali ga subscribe</h3>
  <div class="subscribe grid-x align-middle" style="height: auto;">
      <div class="cell medium-1"></div>
          <div class="cell medium-4" >
              {% csrf_token %}
              {{ subsForm | crispy }}
              <div id="statusForm"></div>
                <br>
                <button class="button" name="submit" id='submit' disabled>Subscribe</button>
          </div>
  </div>

  <!-- The Modal -->
  <div id="myModal" class="modal">

        <!-- Modal content -->
            <div class="modal-content">
                <span class="close">&times;</span>
                <div id='modal-content'>
                    <h3 id='email_delete'>Enter password:</h3>
                    <input type="password" id='password-delete' name='password-delete'>
                    <button id='delete_button' class="button"> Delete </button>
                    <div id="status-deleted"></div>
                </div>
            </div>
  </div>


        <div class="grid-x align-middle">
            <h3>Subscriber</h3>
            <div class="cell medium-2"></div>
            
            <div class="cell medium-8">
                <table id = "list_subscribers" style="margin: auto;">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th width="150">Name</th>
                            <th width="150">Email</th>
                            <th class="text-center"></th>
                          </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
            
            <div class="cell medium-2"></div>
        </div>


</div>
</body>
</html>

story8/templates/navbar.html
{% load static %}
<div class="header">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <a href="{% url 'story8:landing-page' %}">Home</a>
  <a href="{% url 'story8:books' %}">Books</a>
  <a href="{% url 'story11:index' %}">Story 11</a>
</div>